import Head from "next/head";
import AddBkFrom from "../components/listViewPage/AddBkForm";
import BkList from "../components/listViewPage/BkList";
import PageContainer from "../components/common/PageContainer";
import EditBkModal from "../components/listViewPage/EditBkModal";
import Paginate from "../components/listViewPage/Paginate";
import {useEffect,  useState} from "react"

export default function Home() {

const [data, setData] = useState("")

  useEffect(()=>{

    fetch("https://raw.githubusercontent.com/9spokes/coding-challenge/master/data.json").then(
  response=>console.log(response.json())
    )

    // useEffect(() => {
    //   fetch("https://dog.ceo/api/breeds/image/random")
    //   .then(response => response.json())
    //       // 4. Setting *dogImage* to the image url that we received from the response above
    //   .then(data => setDogImage(data.message))
    // },[])


  }, [])
  return (
    <PageContainer>
      <Head>
        <title>Bookmark Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-5">
        <AddBkFrom />
        <BkList />
        <Paginate />
      </main>

      <EditBkModal />
    </PageContainer>
  );
}
