import Head from "next/head";
import AddBkFrom from "../src/components/listViewPage/AddBkForm";
import BkList from "../src/components/listViewPage/BkList";
import PageContainer from "../src/components/common/PageContainer";
import EditBkModal from "../src/components/listViewPage/EditBkModal";
import Paginate from "../src/components/listViewPage/Paginate";

export default function Home() {
  return (
    <PageContainer>
      <Head>
        <title>Bookmark Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="py-5">
        <AddBkFrom />
        <BkList />
        <Paginate />
      </main>

      <EditBkModal />
    </PageContainer>
  );
}
